# Generated by Django 3.2 on 2022-07-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_postvote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('user', 'comment')},
        ),
    ]
