# Generated by Django 3.2 on 2022-07-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_commentvote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('user', 'post')},
        ),
    ]
