# Generated by Django 4.0.5 on 2022-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='main_color',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
