# Generated by Django 3.2 on 2022-07-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_school_main_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
