# Generated by Django 3.2 on 2022-07-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220729_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_on_post',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.comment'),
        ),
    ]
