# Generated by Django 3.2 on 2022-07-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220730_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='number_on_post',
            field=models.IntegerField(default=1),
        ),
    ]
