# Generated by Django 3.2 on 2022-07-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_comment_number_on_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phonelogincode',
            name='user',
        ),
        migrations.DeleteModel(
            name='DirectConversation',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
        migrations.DeleteModel(
            name='PhoneLoginCode',
        ),
    ]
