make all:
	python3 manage.py makemigrations
	python3 manage.py migrate
	python3 manage.py runserver 8005

run:
	python3 manage.py runserver 8005

migrations:
	python3 manage.py makemigrations

migrate:
	python3 manage.py migrate

superuser:
	python3 manage.py createsuperuser


