# Generated by Django 4.0.4 on 2022-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y', upload_to='profile_pictures'),
        ),
    ]
