# Generated by Django 4.0.5 on 2022-06-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tag_post_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
