# Generated by Django 3.2 on 2022-07-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_phonelogincode_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='has_been_verified',
            field=models.BooleanField(default=False),
        ),
    ]
