# Generated by Django 3.2 on 2022-07-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220709_1923'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('poll', None), ('image', None), _connector='OR'), name='post_poll_or_image_check'),
        ),
    ]
