# Generated by Django 3.2 on 2022-07-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220704_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_attending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school'),
        ),
    ]
